version: '3'
services:
  postgres:
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - postgres-network
  python:
    build: .
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge
