name: Build and slim rust-dev container

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  TAG_STEM: rust-dev
  TEST_TAG: test
  LATEST_TAG: latest
  DOCKERFILE_FOLDER: ./rust/.devcontainer
  MAJOR_VERSION: 1
  DSLIM_HTTP_PROBE: false

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # Check out the repository
    - name: Check out the repository
      uses: actions/checkout@v3

    # Set up QEMU
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Login to Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # Build test image
    - name: Build and export to Docker
      uses: docker/build-push-action@v5
      with:
        context: ${{ env.DOCKERFILE_FOLDER }}
        file: ${{ env.DOCKERFILE_FOLDER }}/Dockerfile
        load: true
        push: false
        tags: ${{ env.TAG_STEM }}:${{ env.TEST_TAG }}

    # Test the image before going further
    - name: Test
      run: |
        docker run --rm ${{ env.TAG_STEM }}:${{ env.TEST_TAG }}

    # If the test passed, build the full-size images for all platforms
    - name: Build full-sized images for all platforms
      uses: docker/build-push-action@v5
      with:
        context: ${{ env.DOCKERFILE_FOLDER }}
        file: ${{ env.DOCKERFILE_FOLDER }}/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: false
        tags: ${{ env.TAG_STEM }}:${{ env.LATEST_TAG }}

    # Slim the full-size image
    - name: Slim the full-size images for all platforms
      uses: kitabisa/docker-slim-action@v1
      with:
        platforms: linux/amd64,linux/arm64
        target: ${{ env.TAG_STEM }}:${{ env.LATEST_TAG }}
        tag: "slim-${{ env.MAJOR_VERSION }}.{{ github.run_number }}"

    # Push only the slim image to Docker Hub
    - name: Push slim image to Docker Hub
      run: |
        docker image push ${{ env.TAG_STEM }}:slim-${{ env.MAJOR_VERSION }}.{{ github.run_number }}
